services:
  metatool-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file:
      - ./.env
    restart: always
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - metatool-postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  metatool-remote-hosting:
    build:
      context: ./remote-hosting
      dockerfile: Dockerfile
      target: runner
    env_file:
      - ./.env
    restart: always
    expose:
      - '12007'
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"

  metatool-postgres:
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: metatool
      POSTGRES_USER: metatool
      POSTGRES_PASSWORD: m3t4t00l
    expose:
      - '5432'
    volumes:
      - metatool-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U metatool" ]
      interval: 5s
      timeout: 5s
      retries: 5

  drizzle-migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    command: pnpm drizzle-kit migrate
    env_file:
      - ./.env
    depends_on:
      metatool-postgres:
        condition: service_healthy

volumes:
  metatool-postgres:
    driver: local