# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:20-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install the dependencies
RUN --mount=type=cache,target=/root/.npm npm install --ignore-scripts

# Copy the current directory contents into the container at /app
COPY . .

# Build the app
RUN npm run build

# Use a smaller Node.js runtime image for the final stage
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy only the built files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Set environment variables
ENV NODE_ENV=production

# Install only production dependencies
RUN npm ci --omit=dev

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define environment variable
ENV METATOOL_API_KEY=your_api_key_here

# Run the application
ENTRYPOINT ["node", "dist/index.js"]
